// Generated by CoffeeScript 1.7.1

/**
 * Represents an Image with the intent of it being later diaplayed in a lightbox.
 */

(function() {
  var Box, Image, ImageList, LightB, Navigation,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Image = (function() {

    /**
     * @constructor
     * @param {DOM} The link to an image that originates the Image.
     * @param {ImageList} If the image belongs to a list, the list it belongs to. Or undefined.
     */
    function Image(dom, list) {
      var clickHandler, self;
      this.dom = dom;
      this.list = list;
      self = this;
      clickHandler = function(event) {
        window.LightB.display(self);
        return event.preventDefault();
      };
      this.href = jQuery(this.dom).attr('href');
      jQuery(this.dom).click(clickHandler);
    }

    Image.prototype.href = Image.href;

    Image.prototype.list = Image.list;

    return Image;

  })();


  /**
   * If the DOM originating the Images is a list, an ImageList instead of an Image is created in orter to
   * being able to traverse it in order from a navigation menu.
   */

  ImageList = (function(_super) {
    __extends(ImageList, _super);


    /**
     * @constructor
     * @param {DOM...} A variable number of splatted DOM links to images.
     */

    function ImageList() {
      var arg, args, self;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      self = this;
      args = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = args.length; _i < _len; _i++) {
          arg = args[_i];
          _results.push(new Image(arg, self));
        }
        return _results;
      })();
      this.push.apply(this, args);
    }

    return ImageList;

  })(Array);


  /**
   * Grafical representation and functionality of a navigation menu to traverse in order the images of a list.
   */

  Navigation = (function() {

    /**
     * @constructor
     */
    function Navigation() {
      this.dom = jQuery("<nav class='lightb-nav' style='display:none'></nav>");
      this.prevButton = jQuery("<a class='lightb-prev-extend' href='#'><div class='lightb-prev lightb-button'></div></a>");
      this.nextButton = jQuery("<a class='lightb-next-extend' href='#'><div class='lightb-next lightb-button'></div></a>");
      jQuery(this.dom).append(this.prevButton).append(this.nextButton).click(function(event) {
        return event.stopPropagation();
      });
    }

    Navigation.prototype.dom = Navigation.dom;


    /**
     * Show the navigation menu on screen.
     * Look and function depend on the image being shown.
     * @param {Image} Image that will be shown.
     * @param {DOM} The dom associated with the image.
     */

    Navigation.prototype.show = function(image, imageDom) {
      jQuery(this.dom).show();
      if (image && imageDom) {
        return this.reset(image, imageDom);
      }
    };


    /**
     * Hide the navigation menu.
     */

    Navigation.prototype.hide = function() {
      return jQuery(this.dom).hide();
    };


    /**
     * With each different image being shown, the menu must adapt look and functionality.
     * @param {Image} Image that will be shown.
     * @param {DOM} The dom associated with the image.
     */

    Navigation.prototype.reset = function(image, imageDom) {
      var list;
      list = image.list;
      jQuery(this.dom).width(jQuery(imageDom).width()).find('.off').removeClass('off').find('a').off('click');
      if (list.indexOf(image) === 0) {
        jQuery('.lightb-button', this.prevButton).addClass('off');
      } else {
        jQuery(this.prevButton).on('click', (function(_this) {
          return function() {
            return window.LightB.display(list[list.indexOf(image) - 1]);
          };
        })(this));
      }
      if (list.indexOf(image) === list.length - 1) {
        return jQuery('.lightb-button', this.nextButton).addClass('off');
      } else {
        return jQuery(this.nextButton).on('click', (function(_this) {
          return function() {
            return window.LightB.display(list[list.indexOf(image) + 1]);
          };
        })(this));
      }
    };

    return Navigation;

  })();


  /**
   * The actual lightbox. A dark layer on which to impose the picture.
   */

  Box = (function() {

    /**
     * @constructor
     */
    function Box() {
      this.display = __bind(this.display, this);
      this.hide = __bind(this.hide, this);
      this.show = __bind(this.show, this);
      this.dom = jQuery('<div class="lightb-target off"><a class="lightb-close lightb-button" href="#"></a></div>');
      this.nav = new Navigation;
      jQuery('body').append(this.dom);
      jQuery(this.dom).append(this.nav.dom);
      jQuery(this.dom).on('click', this.hide);
    }


    /**
     * Show the lightbox.
     */

    Box.prototype.show = function() {
      return jQuery(this.dom).show(0, (function(_this) {
        return function() {
          return jQuery(_this.dom).removeClass('off').addClass('on');
        };
      })(this));
    };


    /**
     * Hide the lightbox.
     */

    Box.prototype.hide = function() {
      var handleHide;
      handleHide = (function(_this) {
        return function() {
          jQuery(_this.dom).hide();
          jQuery(_this.dom).find('.lightb-image').remove();
          return _this.nav.hide();
        };
      })(this);
      this.nav.hide();
      jQuery(this.dom).removeClass('on').addClass('off');
      return setTimeout(handleHide, 500);
    };


    /**
     * Display an image. This is the main method to be used.
     * @param {Image} The image to be displayed.
     */

    Box.prototype.display = function(image) {
      var imageDom;
      imageDom = jQuery("<img class='lightb-image' src='" + image.href + "' />");
      jQuery(imageDom).click(function(event) {
        return event.stopPropagation();
      });
      jQuery(this.dom).find('.lightb-image').remove();
      jQuery(this.dom).append(imageDom);
      this.show();
      return imageDom.one('load', (function(_this) {
        return function() {
          if (image.list) {
            return _this.nav.show(image, imageDom);
          }
        };
      })(this));
    };

    return Box;

  })();


  /**
   * The main class of it all.
   * Uses all other classes, initializes the DOM to be used with the lightbox.
   * Attaches behavior to all link-images marked with data-lightbox.
   * Attaches behavior to all elements containing  link-images marked with data-box as well such as lists, layers...
   */

  LightB = (function() {

    /**
     * @constructor
     */
    var LightBKeyHandler;

    function LightB() {
      this.box = new Box;
      this.initialize();
    }


    /**
     * Sets up the DOM, attaching events to all elements marked with data-lightbox.
     */

    LightB.prototype.initialize = function() {
      jQuery(document).on('keyup', LightBKeyHandler);
      return jQuery('[data-lightbox]').each(function(i, elem) {
        var images;
        if (jQuery(elem).is('a')) {
          return new Image(elem);
        } else {
          images = jQuery(elem).find('a:has(>img)').toArray();
          return (function(func, args, ctor) {
            ctor.prototype = func.prototype;
            var child = new ctor, result = func.apply(child, args);
            return Object(result) === result ? result : child;
          })(ImageList, images, function(){});
        }
      });
    };

    LightBKeyHandler = function(e) {
      if (e.which === 27) {
        return window.LightB.box.hide();
      }
    };


    /**
     * The main method that makes it all work. Displays an image in a lightbox.
     * @param {Image} Image to be displayed.
     */

    LightB.prototype.display = function(image) {
      return this.box.display(image);
    };

    return LightB;

  })();


  /*
   * MAIN.
   */

  window.LightB = new LightB;

}).call(this);
